spring.application.name=scalable-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/scalable_backend
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkey
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.filter.dispatcher-types=REQUEST,ERROR,ASYNC
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
server.port=8080